name: FancyCam2
version: 1.3.2
main: FancyCam.MainClass
commands:
  addloop:
    usage: "Usage: /addloop <bounce/normal> <loop-id> <radius> [height] [speed] [bounce:frequency]"
    description:
  loop:
    usage: "Usage: /loop <start> <loop-id> or /loop <stop/list>"
    description:
  editloop:
    usage: "Usage: /editloop <id> <stat> <newvalue>"
    description:
  saveloops:
    usage: "Usage: /saveloops"
    description: "This command is used to save all current loops to file.\nWhen you remove a loop you should execute this command."